language: csharp
dist: trusty
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
- dotnet restore

script:
- dotnet build
- dotnet test ./UniversityManager.Tests/UniversityManager.Tests.csproj
- dotnet test ./UniversityManager.Tests.EndToEnd/UniversityManager.Tests.EndToEnd.csproj